//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.HandBookSale.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class added_books
    {
        public int user_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime add_date { get; set; }
    
        public virtual books books { get; set; }
        public virtual users users { get; set; }
    }
}
