//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.HandBookSale.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.added_books = new HashSet<added_books>();
            this.sold_books = new HashSet<sold_books>();
        }
    
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_author { get; set; }
        public string book_description { get; set; }
        public System.DateTime book_registration { get; set; }
        public double book_cost { get; set; }
        public string book_genre { get; set; }
        public byte[] book_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<added_books> added_books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sold_books> sold_books { get; set; }
    }
}
