//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.HandBookSale.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public System.DateTime user_registration_date { get; set; }
        public string user_address { get; set; }
        public string user_phone { get; set; }
    
        public virtual added_books added_books { get; set; }
        public virtual sold_books sold_books { get; set; }
    }
}
